name: Docs

on:

  push:
    branches:
    - 'master'

  pull_request: ~

  workflow_dispatch: ~

jobs:

  docs:
    name: docs
    runs-on: ubuntu-latest
    steps:
      - name: Start polytope-docs build
        uses: actions/github-script@v4
        with:
          script: |-
            await github.actions.createWorkflowDispatch({
                owner: 'ecmwf-projects',
                repo: 'polytope-docs',
                workflow_id: 'publish.yaml',
                ref: 'master'
            });
